version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - 31.4.0
    - 31.6.0
    - 32.0.0
    - 32.0.1
    - 32.0.2
    - 32.1.0
    - 32.1.1
    - 32.2.0
    - 32.3.1
    - 32.3.2
  - dependency-name: node-html-parser
    versions:
    - 2.1.0
    - 2.2.0
    - 2.2.1
    - 3.0.1
    - 3.0.2
    - 3.0.3
    - 3.0.4
    - 3.1.0
    - 3.1.1
    - 3.1.5
    - 3.1.6
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
  - dependency-name: mocha
    versions:
    - 8.3.0
    - 8.3.1
  - dependency-name: clean-css
    versions:
    - 5.0.1
    - 5.1.0
    - 5.1.1
